custom_configs_users.candidato_registration:
  path: '/cadastro/candidato'
  defaults:
    _title: 'Cadastro de candidato'
    _form: '\Drupal\custom_configs_users\Form\CandidatoRegistrationForm'
  requirements:
    _user_is_logged_in: 'FALSE'

custom_configs_users.candidato_perfil:
  path: '/meu-perfil'
  defaults:
    _title: 'Meu Perfil'
    _controller: '\Drupal\custom_configs_users\Controller\CandidatoPerfilController::view'
  requirements:
    _user_is_logged_in: 'TRUE'
