--
-- PostgreSQL database dump
--

\restrict Al7N1ikqufwEouQhTKplfn5EimsDU1K5BZRgHTVCSCboRpcszAqYQPeG8CX02pA

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: drupal_watchdog; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1367, 0, 'smtp', 'Sending mail to: @to (subject: %subject)', 'a:2:{s:3:"@to";s:35:"DIEGOcandidado <dieps1.0@gmail.com>";s:8:"%subject";s:56:"Detalhes de conta para DIEGOcandidado em Eu Sou Est\303\241gio";}', 6, '', 'http://localhost:8081/cadastro/candidato', 'http://localhost:8081/cadastro/candidato', '172.22.0.1', 1774623345);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1368, 9, 'user', 'Session opened for %name.', 'a:1:{s:5:"%name";s:14:"DIEGOcandidado";}', 6, '', 'http://localhost:8081/user/reset/9/1774623340/1UG-wFFcPGkFkz-oxMkp7xVUFjzm-gMLzKt5LNYJN4Y/login', 'http://localhost:8081/user/reset/9', '172.22.0.1', 1774623383);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1369, 9, 'user', 'User %name used one-time login link at time %timestamp.', 'a:2:{s:5:"%name";s:14:"DIEGOcandidado";s:10:"%timestamp";s:10:"1774623340";}', 6, '', 'http://localhost:8081/user/reset/9/1774623340/1UG-wFFcPGkFkz-oxMkp7xVUFjzm-gMLzKt5LNYJN4Y/login', 'http://localhost:8081/user/reset/9', '172.22.0.1', 1774623383);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1370, 1, 'locale', 'Updated JavaScript translation file for the language %language.', 'a:1:{s:9:"%language";s:18:"Portuguese, Brazil";}', 5, '', 'http://localhost:8081/admin/structure/menu/manage/links-rapidos', 'http://localhost:8081/', '172.22.0.1', 1774623448);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1371, 1, 'locale', 'Updated JavaScript translation file for the language %language.', 'a:1:{s:9:"%language";s:18:"Portuguese, Brazil";}', 5, '', 'http://localhost:8081/admin/structure/menu/manage/para-empresas', 'http://localhost:8081/', '172.22.0.1', 1774623448);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1372, 1, 'locale', 'Updated JavaScript translation file for the language %language.', 'a:1:{s:9:"%language";s:18:"Portuguese, Brazil";}', 5, '', 'http://localhost:8081/admin/people', 'http://localhost:8081/batch?id=37&op=start', '172.22.0.1', 1774623767);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1373, 1, 'locale', 'Updated JavaScript translation file for the language %language.', 'a:1:{s:9:"%language";s:18:"Portuguese, Brazil";}', 5, '', 'http://localhost:8081/user/9/edit?destination=%2Fadmin%2Fpeople', 'http://localhost:8081/admin/people', '172.22.0.1', 1774624057);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1374, 0, 'cron', 'Starting execution of @module_cron().', 'a:1:{s:7:"@module";s:18:"announcements_feed";}', 6, '', 'http://localhost:8081/user/9/edit?destination=%2Fadmin%2Fpeople', 'http://localhost:8081/admin/people', '172.22.0.1', 1774624059);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1375, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:5:"dblog";s:16:"@module_previous";s:18:"announcements_feed";s:5:"@time";s:6:"0.73ms";}', 6, '', 'http://localhost:8081/user/9/edit?destination=%2Fadmin%2Fpeople', 'http://localhost:8081/admin/people', '172.22.0.1', 1774624059);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1376, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:5:"field";s:16:"@module_previous";s:5:"dblog";s:5:"@time";s:6:"6.91ms";}', 6, '', 'http://localhost:8081/user/9/edit?destination=%2Fadmin%2Fpeople', 'http://localhost:8081/admin/people', '172.22.0.1', 1774624059);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1377, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:4:"file";s:16:"@module_previous";s:5:"field";s:5:"@time";s:7:"33.32ms";}', 6, '', 'http://localhost:8081/user/9/edit?destination=%2Fadmin%2Fpeople', 'http://localhost:8081/admin/people', '172.22.0.1', 1774624059);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1378, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"locale";s:16:"@module_previous";s:4:"file";s:5:"@time";s:7:"72.38ms";}', 6, '', 'http://localhost:8081/user/9/edit?destination=%2Fadmin%2Fpeople', 'http://localhost:8081/admin/people', '172.22.0.1', 1774624059);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1379, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:4:"node";s:16:"@module_previous";s:6:"locale";s:5:"@time";s:6:"0.06ms";}', 6, '', 'http://localhost:8081/user/9/edit?destination=%2Fadmin%2Fpeople', 'http://localhost:8081/admin/people', '172.22.0.1', 1774624059);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1380, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"search";s:16:"@module_previous";s:4:"node";s:5:"@time";s:8:"133.19ms";}', 6, '', 'http://localhost:8081/user/9/edit?destination=%2Fadmin%2Fpeople', 'http://localhost:8081/admin/people', '172.22.0.1', 1774624059);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1381, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"system";s:16:"@module_previous";s:6:"search";s:5:"@time";s:8:"136.75ms";}', 6, '', 'http://localhost:8081/user/9/edit?destination=%2Fadmin%2Fpeople', 'http://localhost:8081/admin/people', '172.22.0.1', 1774624059);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1382, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"update";s:16:"@module_previous";s:6:"system";s:5:"@time";s:8:"335.76ms";}', 6, '', 'http://localhost:8081/user/9/edit?destination=%2Fadmin%2Fpeople', 'http://localhost:8081/admin/people', '172.22.0.1', 1774624059);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1383, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:7:"webform";s:16:"@module_previous";s:6:"update";s:5:"@time";s:7:"25.97ms";}', 6, '', 'http://localhost:8081/user/9/edit?destination=%2Fadmin%2Fpeople', 'http://localhost:8081/admin/people', '172.22.0.1', 1774624059);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1384, 0, 'cron', 'Execution of @module_previous_cron() took @time.', 'a:2:{s:16:"@module_previous";s:7:"webform";s:5:"@time";s:7:"87.35ms";}', 6, '', 'http://localhost:8081/user/9/edit?destination=%2Fadmin%2Fpeople', 'http://localhost:8081/admin/people', '172.22.0.1', 1774624059);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1385, 0, 'cron', 'Cron run completed.', 'a:0:{}', 6, '', 'http://localhost:8081/user/9/edit?destination=%2Fadmin%2Fpeople', 'http://localhost:8081/admin/people', '172.22.0.1', 1774624059);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1386, 1, 'user', 'Deleted user: %name %email.', 'a:2:{s:5:"%name";s:14:"DIEGOcandidado";s:6:"%email";s:20:"<dieps1.0@gmail.com>";}', 5, '', 'http://localhost:8081/batch?_format=json&id=38&op=do', 'http://localhost:8081/batch?id=38&op=start', '172.22.0.1', 1774624315);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1387, 0, 'smtp', 'Sending mail to: @to (subject: %subject)', 'a:2:{s:3:"@to";s:35:"diegocandidato <dieps1.0@gmail.com>";s:8:"%subject";s:56:"Detalhes de conta para diegocandidato em Eu Sou Est\303\241gio";}', 6, '', 'http://localhost:8081/cadastro/candidato', 'http://localhost:8081/cadastro/candidato', '172.22.0.1', 1774624489);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1388, 10, 'user', 'Session opened for %name.', 'a:1:{s:5:"%name";s:14:"diegocandidato";}', 6, '', 'http://localhost:8081/user/reset/10/1774624485/FSIZRsFwhPyxR_-BJLQ8KlzU-L5BP28V1i09H3tONs4/login', 'http://localhost:8081/user/reset/10', '172.22.0.1', 1774624606);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1389, 10, 'user', 'User %name used one-time login link at time %timestamp.', 'a:2:{s:5:"%name";s:14:"diegocandidato";s:10:"%timestamp";s:10:"1774624485";}', 6, '', 'http://localhost:8081/user/reset/10/1774624485/FSIZRsFwhPyxR_-BJLQ8KlzU-L5BP28V1i09H3tONs4/login', 'http://localhost:8081/user/reset/10', '172.22.0.1', 1774624606);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1390, 10, 'user', 'Session closed for %name.', 'a:1:{s:5:"%name";s:14:"diegocandidato";}', 6, '', 'http://localhost:8081/user/logout?token=bBGB6ylmvg3phjXeR1t8nv8cWe-YDPzKtF8YvfLaBL4', 'http://localhost:8081/meu-perfil', '172.22.0.1', 1774625389);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1391, 1, 'locale', 'Updated JavaScript translation file for the language %language.', 'a:1:{s:9:"%language";s:18:"Portuguese, Brazil";}', 5, '', 'http://localhost:8081/admin/structure/menu/manage/para-empresas', 'http://localhost:8081/admin/structure/menu/item/6/edit?destination=/admin/structure/menu/manage/para-empresas', '172.22.0.1', 1774625427);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1392, 1, 'user', 'Deleted user: %name %email.', 'a:2:{s:5:"%name";s:14:"diegocandidato";s:6:"%email";s:20:"<dieps1.0@gmail.com>";}', 5, '', 'http://localhost:8081/batch?_format=json&id=39&op=do', 'http://localhost:8081/batch?id=39&op=start', '172.22.0.1', 1774625582);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1393, 1, 'locale', 'Updated JavaScript translation file for the language %language.', 'a:1:{s:9:"%language";s:18:"Portuguese, Brazil";}', 5, '', 'http://localhost:8081/', 'http://localhost:8081/', '172.22.0.1', 1774625813);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1394, 0, 'smtp', 'Sending mail to: @to (subject: %subject)', 'a:2:{s:3:"@to";s:32:"degoempresa <dieps1.0@gmail.com>";s:8:"%subject";s:53:"Detalhes de conta para degoempresa em Eu Sou Est\303\241gio";}', 6, '', 'http://localhost:8081/cadastro/empresa', 'http://localhost:8081/cadastro/empresa', '172.22.0.1', 1774625887);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1395, 0, 'cron', 'Starting execution of @module_cron().', 'a:1:{s:7:"@module";s:18:"announcements_feed";}', 6, '', 'http://localhost:8081/', 'http://localhost:8081/', '172.22.0.1', 1774635259);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1396, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:5:"dblog";s:16:"@module_previous";s:18:"announcements_feed";s:5:"@time";s:7:"720.4ms";}', 6, '', 'http://localhost:8081/', 'http://localhost:8081/', '172.22.0.1', 1774635260);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1397, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:5:"field";s:16:"@module_previous";s:5:"dblog";s:5:"@time";s:6:"5.93ms";}', 6, '', 'http://localhost:8081/', 'http://localhost:8081/', '172.22.0.1', 1774635260);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1398, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:4:"file";s:16:"@module_previous";s:5:"field";s:5:"@time";s:7:"23.09ms";}', 6, '', 'http://localhost:8081/', 'http://localhost:8081/', '172.22.0.1', 1774635260);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1399, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"locale";s:16:"@module_previous";s:4:"file";s:5:"@time";s:6:"4.63ms";}', 6, '', 'http://localhost:8081/', 'http://localhost:8081/', '172.22.0.1', 1774635260);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1400, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:4:"node";s:16:"@module_previous";s:6:"locale";s:5:"@time";s:6:"0.85ms";}', 6, '', 'http://localhost:8081/', 'http://localhost:8081/', '172.22.0.1', 1774635260);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1401, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"search";s:16:"@module_previous";s:4:"node";s:5:"@time";s:6:"71.1ms";}', 6, '', 'http://localhost:8081/', 'http://localhost:8081/', '172.22.0.1', 1774635260);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1402, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"system";s:16:"@module_previous";s:6:"search";s:5:"@time";s:8:"144.43ms";}', 6, '', 'http://localhost:8081/', 'http://localhost:8081/', '172.22.0.1', 1774635260);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1403, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"update";s:16:"@module_previous";s:6:"system";s:5:"@time";s:8:"603.63ms";}', 6, '', 'http://localhost:8081/', 'http://localhost:8081/', '172.22.0.1', 1774635261);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1404, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:7:"webform";s:16:"@module_previous";s:6:"update";s:5:"@time";s:8:"5464.5ms";}', 6, '', 'http://localhost:8081/', 'http://localhost:8081/', '172.22.0.1', 1774635267);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1405, 0, 'cron', 'Execution of @module_previous_cron() took @time.', 'a:2:{s:16:"@module_previous";s:7:"webform";s:5:"@time";s:8:"142.95ms";}', 6, '', 'http://localhost:8081/', 'http://localhost:8081/', '172.22.0.1', 1774635267);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1406, 0, 'cron', 'Cron run completed.', 'a:0:{}', 6, '', 'http://localhost:8081/', 'http://localhost:8081/', '172.22.0.1', 1774635267);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1407, 0, 'cron', 'Starting execution of @module_cron().', 'a:1:{s:7:"@module";s:18:"announcements_feed";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774701085);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1408, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:5:"dblog";s:16:"@module_previous";s:18:"announcements_feed";s:5:"@time";s:9:"1650.68ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774701086);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1409, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:5:"field";s:16:"@module_previous";s:5:"dblog";s:5:"@time";s:6:"1.24ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774701086);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1410, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:4:"file";s:16:"@module_previous";s:5:"field";s:5:"@time";s:7:"15.46ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774701086);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1411, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"locale";s:16:"@module_previous";s:4:"file";s:5:"@time";s:5:"4.4ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774701086);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1412, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:4:"node";s:16:"@module_previous";s:6:"locale";s:5:"@time";s:6:"0.59ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774701086);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1413, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"search";s:16:"@module_previous";s:4:"node";s:5:"@time";s:7:"59.04ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774701086);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1414, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"system";s:16:"@module_previous";s:6:"search";s:5:"@time";s:8:"125.66ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774701087);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1415, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"update";s:16:"@module_previous";s:6:"system";s:5:"@time";s:8:"285.59ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774701087);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1416, 0, 'cron', 'Attempting to re-run cron while it is already running.', 'a:0:{}', 4, '', 'http://localhost:8081/contextual/render?theme=default', 'http://localhost:8081/', '172.22.0.1', 1774701088);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1417, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:7:"webform";s:16:"@module_previous";s:6:"update";s:5:"@time";s:9:"5147.63ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774701092);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1418, 0, 'cron', 'Execution of @module_previous_cron() took @time.', 'a:2:{s:16:"@module_previous";s:7:"webform";s:5:"@time";s:8:"135.15ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774701092);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1419, 0, 'cron', 'Cron run completed.', 'a:0:{}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774701092);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1420, 0, 'cron', 'Starting execution of @module_cron().', 'a:1:{s:7:"@module";s:18:"announcements_feed";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774716334);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1421, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:5:"dblog";s:16:"@module_previous";s:18:"announcements_feed";s:5:"@time";s:6:"0.66ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774716334);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1422, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:5:"field";s:16:"@module_previous";s:5:"dblog";s:5:"@time";s:6:"1.37ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774716334);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1423, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:4:"file";s:16:"@module_previous";s:5:"field";s:5:"@time";s:7:"17.14ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774716334);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1424, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"locale";s:16:"@module_previous";s:4:"file";s:5:"@time";s:6:"3.05ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774716334);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1425, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:4:"node";s:16:"@module_previous";s:6:"locale";s:5:"@time";s:6:"0.91ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774716334);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1426, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"search";s:16:"@module_previous";s:4:"node";s:5:"@time";s:7:"94.03ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774716334);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1427, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"system";s:16:"@module_previous";s:6:"search";s:5:"@time";s:8:"163.96ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774716334);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1428, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:6:"update";s:16:"@module_previous";s:6:"system";s:5:"@time";s:8:"307.66ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774716334);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1429, 0, 'cron', 'Attempting to re-run cron while it is already running.', 'a:0:{}', 4, '', 'http://localhost:8081/contextual/render?theme=default', 'http://localhost:8081/', '172.22.0.1', 1774716337);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1430, 0, 'cron', 'Starting execution of @module_cron(), execution of @module_previous_cron() took @time.', 'a:3:{s:7:"@module";s:7:"webform";s:16:"@module_previous";s:6:"update";s:5:"@time";s:9:"6286.71ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774716341);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1431, 0, 'cron', 'Execution of @module_previous_cron() took @time.', 'a:2:{s:16:"@module_previous";s:7:"webform";s:5:"@time";s:7:"98.85ms";}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774716341);
INSERT INTO public.drupal_watchdog (wid, uid, type, message, variables, severity, link, location, referer, hostname, "timestamp") VALUES (1432, 0, 'cron', 'Cron run completed.', 'a:0:{}', 6, '', 'http://localhost:8081/', '', '172.22.0.1', 1774716341);


--
-- Name: drupal_watchdog_wid_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.drupal_watchdog_wid_seq', 1432, true);


--
-- PostgreSQL database dump complete
--

\unrestrict Al7N1ikqufwEouQhTKplfn5EimsDU1K5BZRgHTVCSCboRpcszAqYQPeG8CX02pA

